version: "2"
services:
  app:
    build: .
    env_file: .env
    depends_on:
      - postgres
    environment:
      POSTGRES: postgres://user:postgres@postgres:5432/db
      NODE_ENV: development
      PORT: 5000
      SECRET: HUBHUBHUB
      SECRETS: HUPHUTHYUTTYUN
      API: 28965cf068f3c6098d00fff87fe38b40
    ports:
      - "5000:5000"
    command: npm run tests
    volumes:
      - .:/app/
      - /app/node_modules
    
  postgres:
    image: postgres:10.4
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db