name: test-integration
on: [push]
jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:10.18-jessie

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: user
          POSTGRES_HOST: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: db
          POSTGRES_PORT: 5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: use checkout 
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: install
        run: npm install
      - name: start the server
        run: npm run build
        env:
          POSTGRES: postgres://user:postgres@postgres:5432/db
          POSTGRES_PORT: 5432
          POSTGRES_USER: user
          NODE_ENV: production
          SECRET: HUBHUBHUB
          SECRETS: HUPHUTHYUTTYUN
          API: 28965cf068f3c6098d00fff87fe38b40
      - name: start test
        run: npm run test
